name: osago_bloc_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.6.1


dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.0
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  country_icons: ^3.0.0
  intl: any
  flutter_selectable_cards: ^0.0.2
  shared_preferences: ^2.5.3
  pdf: ^3.11.3
  path_provider: ^2.1.5
  permission_handler: ^12.0.0+1
  open_file: ^3.5.10
  google_fonts: ^6.2.1
  flutter_credit_card: ^4.1.0
  qr_flutter: ^4.1.0
  firebase_storage: ^12.4.5
  url_launcher: ^6.3.1
  animated_splash_screen: ^1.3.0
  flutter_native_splash: ^2.4.6
  lottie: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:
  generate: true
  uses-material-design: true


  assets:
    - assets/images/pdf_background.png
    - assets/logo/


  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf

