// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBh1OW3Xb1cyokEEnGtIQma-JTnAzbccNU',
    appId: '1:743525951455:web:9da4de1b91759e59fe866a',
    messagingSenderId: '743525951455',
    projectId: 'osago-bloc',
    authDomain: 'osago-bloc.firebaseapp.com',
    storageBucket: 'osago-bloc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCR8Kqh-U5KnuQfipfFArWOH179pOUBbvI',
    appId: '1:743525951455:android:99cdbdd745bfc8f4fe866a',
    messagingSenderId: '743525951455',
    projectId: 'osago-bloc',
    storageBucket: 'osago-bloc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3g4uZSGsa8NAfSKkNJWnVCPAKiIRKztI',
    appId: '1:743525951455:ios:9bd6a2790f22bc9bfe866a',
    messagingSenderId: '743525951455',
    projectId: 'osago-bloc',
    storageBucket: 'osago-bloc.firebasestorage.app',
    iosBundleId: 'com.example.osagoBlocApp',
  );
}
